#!sh
# installer script to install vimdot
echo "* vimdot installer v1"
INSTALL_PATH=~/.vim/pack/plugins/start

echo -------------------------------------------------

echo "* copying vimrc"
cp .vimrc ~

echo -------------------------------------------------

# steps:
# 0. copy the vimrc file
# 1. read the plugins file.
# 2. determine which ones should be installed.
# 3. install the plugins.

echo "* installing plugins"

# setup directory
cp -r .vim ~

# install the plugins
silent_git() {
    url=https://github.com/$1
    name=${1##*/}
    loc=${INSTALL_PATH}/$name
    if [ ! -d $loc ]; then
        git clone --depth=1 $url $loc --quiet
        echo "+ $name"
    fi
}

while read -r plugin; do
if [ $plugin ]; then
    silent_git $plugin &
fi
done <./plugins
wait

echo -------------------------------------------------

echo "* finished installing!"
