#!sh
# installer script to install vimdot
echo "* vimdot installer v1"

# steps:
# 0. copy the vimrc file
# 1. read the plugins file.
# 2. determine which ones should be installed.
# 3. install the plugins.
