#!sh
# update:
# 1. read the plugins file
# 2. git pull each one

echo "* vimdot plugin updater"
INSTALL_PATH=~/.vim/pack/plugins/start
OPT_PATH=~/.vim/pack/plugins/opt

# helper func
beginswith() { case $2 in "$1"*) true;; *) false;; esac; }

echo -------------------------------------------------

echo "* updating plugins"

silent_pull() {
    if beginswith opt: $1; then
        parsed=$(echo $1 | cut -d":" -f2)
        name=${parsed##*/}
        loc=${OPT_PATH}/$name
    else
        name=${1##*/}
        loc=${INSTALL_PATH}/$name
    fi

    if [ -d $loc ]; then  # pull only if it is installed
        cd $loc
        git fetch --depth=1 --quiet
        git reset --hard @{u} --quiet
        echo "~ $name"
    fi
}

while read -r plugin; do
if [ $plugin ]; then
    silent_pull $plugin &
fi
done <./plugins
wait

echo -------------------------------------------------

echo "* finished updating plugins"
